$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: AzureML-Deploy-Samples-gpu
display_name: deploy_azureml_textclassificationsinglelabel

# You can change path to your custom files by registering in Data and use their 'Named asset URI' below
inputs:
  # dataset files
  # There are several ways to provide file, if its a data in
  # azureml:<<datasetname>>@latest or azureml:<<datasetname>>:<<version>>
  # azureml://subscriptions/<<subscriptionname>>/resourcegroups/<<resourcegroupname>>/workspaces/<<workspacename>>/datastores/workspaceblobstore/paths/PATH
  deployment_type: cpu
  cpu_deployment_name: cpu-test
 
  cpu_online_endpoint_name: cpu-online-sl-class-nlp-dev3
 
  cpu_instance_type: Standard_F16s_v2

  traffic_allocation: 100
  instance_count: 1

  apply_ort: "false"
  apply_deepspeed: "false"
  description: Creating Online endpoint to deploy NLP model --
  name_for_registered_model: sample-model-single-label-classification
  model_path: azureml:sample-model-single-label-classification:7

jobs:
  cpu_create_online_endpoint:
    type: command
    component: ../code/components/create_online_deployment.yaml
    compute: sample-managed-id-cluster
    inputs:
      deployment_name: ${{parent.inputs.cpu_deployment_name}}
      endpoint_name: ${{parent.inputs.cpu_online_endpoint_name}}
      model_path : ${{parent.inputs.model_path}}
      instance_type : ${{parent.inputs.cpu_instance_type}}
      instance_count : ${{parent.inputs.instance_count}}
      traffic_allocation : ${{parent.inputs.traffic_allocation}}