$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: AzureML-Train-Finetune-Samples
display_name: bert_base_uncased_pipeline_run_cli_singlelabel

settings:
    force_rerun: False 


# You can change path to your custom files by registering in Data and use their 'Named asset URI' below
inputs:
  # dataset files
  # There are several ways to provide file, if its a data in
  # azureml:<<datasetname>>@latest or azureml:<<datasetname>>:<<version>>
  # azureml://subscriptions/<<subscriptionname>>/resourcegroups/<<resourcegroupname>>/workspaces/<<workspacename>>/datastores/workspaceblobstore/paths/PATH
  name_for_registered_model: sample_model_single_label_classification

  train_file:
    path: azureml:MultiLabelClassification_train@latest #Input 
    type: uri_file
  validation_file:
    path: azureml:MultiLabelClassification_validation@latest
    type: uri_file
  test_file:
    path: azureml:MultiLabelClassification_test@latest
    type: uri_file
  # deepspeed config files
  ds_finetune:
    path: ../deepspeed_configs/zero1.json
    type: uri_file
  ds_inference:
    path: ../deepspeed_configs/zero3.json
    type: uri_file

jobs:
  model_selection:
    type: command
    component: azureml://registries/azureml-preview/components/textclassificationsinglelabel_modelselection/versions/0.0.12
    compute: sample-preprocess-cluster
    inputs:
      #huggingface_id: bert-base-uncased
      model_id: bert-base-uncased
    outputs:
      output_dir:
        type: uri_folder

  data_pre_process:
    type: command
    component: azureml://registries/azureml-preview/components/textclassificationsinglelabel_datapreprocessing/versions/0.0.12
    compute: sample-preprocess-cluster
    inputs:
      model_path: ${{parent.jobs.model_selection.outputs.output_dir}}
      train_file_path: ${{parent.inputs.train_file}}
      valid_file_path: ${{parent.inputs.validation_file}}
      sentence1_key: sentence
      sentence2_key: ""
      label_key: label
    outputs:
      output_dir:
        type: uri_folder
  
  finetuning:
    type: command
    component: azureml://registries/azureml-preview/components/textclassificationsinglelabel_finetuning/versions/0.0.12
    compute: sample-finetune-cluster
    
    inputs:
      model_path: ${{parent.jobs.model_selection.outputs.output_dir}}
      dataset_path: ${{parent.jobs.data_pre_process.outputs.output_dir}}
      lora_alpha: 128
      lora_r: 8
      lora_dropout: 0.0
      epochs: 1
      learning_rate: 2e-5
      train_batch_size: 1
      valid_batch_size: 1
      apply_deepspeed: "true"
      apply_ort: "true"
      apply_lora: "false"
      merge_lora_weights: "true"
      auto_find_batch_size: "false"
      save_as_mlflow_model: "true"
    outputs:
      pytorch_model_folder:
        type: uri_folder
      mlflow_model_folder:
        type: mlflow_model


  evaluate_model:
    type: command
    component: azureml://registries/azureml-preview/components/evaluate_model/versions/0.0.17
    compute: sample-finetune-cluster
    inputs:
      task: text-classification
      test_data: ${{parent.inputs.validation_file}}
      mlflow_model: ${{parent.jobs.finetuning.outputs.mlflow_model_folder}}
      test_data_label_column_name: label
      test_data_input_column_names: sentence
      device: gpu

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    compute: sample-managed-id-cluster
    inputs:
      model_path: ${{parent.jobs.finetuning.outputs.mlflow_model_folder}}
      model_name: ${{parent.inputs.name_for_registered_model}}
      model_type: mlflow_model
      registry_name: ""